name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t quiz .
        docker images
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Tag Docker image
      run: docker tag quiz ${{ secrets.DOCKER_USERNAME }}/quiz:${GITHUB_SHA}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz:${GITHUB_SHA}

    - name: Configure AWS CLI
      run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          
    - name: List ECS Clusters
      run: |
        ecs_clusters=$(aws ecs describe-clusters --query "clusters[*].clusterName" --output json)
        echo "ECS Clusters: $ecs_clusters"

    - name: Get current ECS task definition revision
      id: ecs-task-revision
      run: echo "::set-output name=revision::$(aws ecs describe-task-definition --task-definition Task1-chandana-definition --query 'taskDefinition.revision')"

    - name: Update ECS service to use the latest task definition
      run: |
          aws ecs update-service --cluster chandana-quiz-app --service quiz-app --task-definition Task1-chandana-definition:${{ steps.ecs-task-revision.outputs.revision }} --debug

